In [1]:
import pandas as pd 
import numpy as np
import sklearn 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("../data/interim/hourly_energy.csv")
df.head()

             timestamp  energy_kwh.1
0  2025-09-20 05:00:00        276.50
1  2025-09-20 06:00:00        269.25
2  2025-09-20 07:00:00        286.75
3  2025-09-20 08:00:00        228.00
4  2025-09-20 09:00:00        171.75

In [7]:
import pandas as pd

# load file
df = pd.read_csv("../data/interim/SUB_S_clean_withoutgrouping.csv")

# convert to datetime (important)
df["cleaned bucket"] = pd.to_datetime(df["cleaned bucket"])

# group by bucket and sum energy
hourly_sum = (
    df.groupby("cleaned bucket", as_index=False)["energy_kwh.1"]
    .sum()
)

# sort by time
hourly_sum = hourly_sum.sort_values("cleaned bucket")

print(hourly_sum)

          cleaned bucket  energy_kwh.1
0    2025-09-20 05:00:00        276.50
1    2025-09-20 06:00:00        269.25
2    2025-09-20 07:00:00        286.75
3    2025-09-20 08:00:00        228.00
4    2025-09-20 09:00:00        171.75
...                  ...           ...
2567 2026-02-26 07:00:00        227.50
2568 2026-02-26 08:00:00        203.50
2569 2026-02-26 09:00:00        259.75
2570 2026-02-26 10:00:00        199.50
2571 2026-02-26 12:00:00        294.50

[2572 rows x 2 columns]

In [8]:
hourly_sum.to_csv("../data/interim/hourly_energy.csv", index=False)

In [10]:
df = pd.read_csv("../data/interim/cleaned_weather.csv")
df.head()

,temp_hi,bar,dew_in,temp_in,pt_dew,index_thsw,index_uv,hum_out,dose_uv,dd_heat,...,emc_in,rate_rain,out_temp,speed_hi,speed_wind,tx_wind,hum_in,date,time,timestamp
0,26.9,29.878,22.4,27.4,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2/25/2025 11:20
1,26.9,29.878,22.4,27.4,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2/25/2025 11:20
2,26.9,29.878,22.4,27.4,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2/25/2025 11:20
3,27.2,29.884,22.3,28.1,22.8,28.9,0.0,77,0.0,0,...,12.95,0.0,27.2,0.0,0.0,1,71,2/25/2025,11:40:00,2/25/2025 11:40
4,27.2,29.884,22.3,28.1,22.8,28.9,0.0,77,0.0,0,...,12.95,0.0,27.2,0.0,0.0,1,71,2/25/2025,11:40:00,2/25/2025 11:40

In [11]:
print(df.columns)

Index(['temp_hi', 'bar', 'dew_in', 'temp_in', 'pt_dew', 'index_thsw',
       'index_uv', 'hum_out', 'dose_uv', 'dd_heat', 'temp_low',
       'density_in_air', 'rain', 'run_wind', 'emc_in', 'rate_rain', 'out_temp',
       'speed_hi', 'speed_wind', 'tx_wind', 'hum_in', 'date', 'time',
       'timestamp'],
      dtype='object')

In [12]:
df_clean = df.drop_duplicates(subset="timestamp", keep="first")

In [13]:
df_clean = df_clean.sort_values("timestamp")

In [14]:
df_clean = df_clean.reset_index(drop=True)

In [16]:
df.head()

,temp_hi,bar,dew_in,temp_in,pt_dew,index_thsw,index_uv,hum_out,dose_uv,dd_heat,...,emc_in,rate_rain,out_temp,speed_hi,speed_wind,tx_wind,hum_in,date,time,timestamp
0,26.9,29.878,22.4,27.4,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2/25/2025 11:20
1,26.9,29.878,22.4,27.4,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2/25/2025 11:20
2,26.9,29.878,22.4,27.4,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2/25/2025 11:20
3,27.2,29.884,22.3,28.1,22.8,28.9,0.0,77,0.0,0,...,12.95,0.0,27.2,0.0,0.0,1,71,2/25/2025,11:40:00,2/25/2025 11:40
4,27.2,29.884,22.3,28.1,22.8,28.9,0.0,77,0.0,0,...,12.95,0.0,27.2,0.0,0.0,1,71,2/25/2025,11:40:00,2/25/2025 11:40

In [17]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [19]:
df = pd.read_csv("../data/interim/cleaned_weather.csv")

df["timestamp"] = pd.to_datetime(df["timestamp"])

df_clean = (
    df.drop_duplicates(subset="timestamp", keep="first")
      .sort_values("timestamp")
      .reset_index(drop=True)
)

df_clean.to_csv("../data/interim/cleaned_data.csv", index=False)

In [20]:
print("cleaned_weather.csv")

cleaned_weather.csv

In [21]:
df

,temp_hi,bar,dew_in,temp_in,pt_dew,index_thsw,index_uv,hum_out,dose_uv,dd_heat,...,emc_in,rate_rain,out_temp,speed_hi,speed_wind,tx_wind,hum_in,date,time,timestamp
0,26.90,29.878,22.4,27.40,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2025-02-25 11:20:00
1,26.90,29.878,22.4,27.40,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2025-02-25 11:20:00
2,26.90,29.878,22.4,27.40,22.4,28.5,0.0,77,0.0,0,...,13.92,0.0,26.8,0.0,0.0,1,74,2/25/2025,11:20:00,2025-02-25 11:20:00
3,27.20,29.884,22.3,28.10,22.8,28.9,0.0,77,0.0,0,...,12.95,0.0,27.2,0.0,0.0,1,71,2/25/2025,11:40:00,2025-02-25 11:40:00
4,27.20,29.884,22.3,28.10,22.8,28.9,0.0,77,0.0,0,...,12.95,0.0,27.2,0.0,0.0,1,71,2/25/2025,11:40:00,2025-02-25 11:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28752,51.22,29.820,24.4,46.11,24.4,38.1,0.7,70,0.7,0,...,13.25,0.0,30.4,13.0,4.0,1,71,2/26/2026,10:45:16,2026-02-26 10:45:00
28753,51.22,29.820,24.4,46.11,24.4,38.1,0.7,70,0.7,0,...,13.25,0.0,30.4,13.0,4.0,1,71,2/26/2026,10:45:16,2026-02-26 10:45:00
28754,51.22,29.830,22.8,46.11,22.8,34.8,0.0,70,0.0,0,...,13.25,0.0,28.9,13.0,4.0,1,68,2/26/2026,12:26:39,2026-02-26 12:26:00
28755,51.22,29.840,22.2,46.11,22.2,33.7,0.0,69,0.0,0,...,13.25,0.0,28.6,13.0,6.0,1,68,2/26/2026,12:41:11,2026-02-26 12:41:00
28756,51.22,29.840,22.2,46.22,22.2,33.1,0.0,70,0.0,0,...,13.25,0.0,28.3,13.0,6.0,1,68,2/26/2026,12:56:33,2026-02-26 12:56:00

In [23]:
import pandas as pd

df = pd.read_csv("../data/interim/cleaned_data.csv")

df["timestamp"] = pd.to_datetime(df["timestamp"])

df["hour_bucket"] = df["timestamp"].dt.floor("h")

df_hourly = (
    df.groupby("hour_bucket")
    .mean(numeric_only=True)
    .reset_index()
)

df_hourly = df_hourly.rename(columns={"hour_bucket": "timestamp"})

df_hourly = df_hourly.sort_values("timestamp")

df_hourly.to_csv("../data/interim/weather_hourly.csv", index=False)